name: uptime-kuma

services:
  uptime-kuma:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:latest
    networks:
      - uptime-net
    volumes:
      - uptime-kuma:/app/data
    restart: always

networks:
  uptime-net:
  driver: bridge

volumes:
  uptime-kuma:
